### PR TITLE
Issue 128 - fixes helm_repo_path in "Steps to install or upgrade to Component Pack 8"

### PR DESCRIPTION
**Pull request by Leyrer-PNP**
Fixes the  value for the <<helm_repo_path>> given in the section "Log in to a Harbor OCI registry" of "Steps to install or upgrade to Component Pack 8".

Wrong: `<<helm_repo_path>> is the Harbor repository to log into, that is https://hclcr.io`
Correct: `<<helm_repo_path>> is the Harbor repository to log into, that is https://hclcr.io/chartrepo/cnx`

@erika-dg

### CODE REVIEW

**Comment by sabrina-yee** [comment]
Hi @Leyrer-PNP, the `helm registry login` command just requires a hostname so the `/chartrepo/cnx` is not needed.

**Comment by wickerlhcl** [comment]
I recently tried @sabrina-yee and it did not work and I ended up in an error 401.

**Comment by sabrina-yee** [comment]
Could you paste in the results?  Here is mine when I tried it:

```
[sabrinayee@vm1 ~]$ helm registry login -u sabrina.yee@hcl.com https://hclcr.io
Password:
Login Succeeded

[sabrinayee@vm1 ~]$
[sabrinayee@vm1 ~]$ helm registry login -u sabrina.yee@hcl.com -p <_my password_> https://hclcr.io
WARNING: Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
```

Will `https://hclcr.io/cnx` work?

**Comment by wickerlhcl** [comment]
Have you tried with customer rather than internal credentials ?

**Comment by sabrina-yee** [comment]
> Have you tried with customer rather than internal credentials ?

This is using a "Limited Guest" test user:

```
helm registry login -u <_my limited guest_> https://hclcr.io
Password:
Login Succeeded
```

The reason I'm trying to avoid using `chartrepo` is we've switched to OCI and ChartMuseum is being depreciated.  If `https://hclcr.io` doesn't work for some users, I'm curious if `https://hclcr.io/cnx` would work.  Your feedback is appreciated, thanks.

**Comment by erika-dg** [comment]
Thanks for investigating Sabrina, I see no action is needed so closing out this PR.

**Pull request closed without merging**
